extends SceneTree

## T-SNS-UI Look lift: renders the build-grid / portrait thumbnails from the
## game's own building views (ProductionBuildingView3D: the project-authored
## opening_style models, plus KayKit CC0 props where the view adds them).
## Offline tool: run under a display (xvfb-run on the box), never at runtime.
##
##   xvfb-run -a -s "-screen 0 1280x720x24" godot --path . --script res://tools/render_building_thumbnails.gd
##
## Writes assets/settlement3d/runtime/interface/thumbs/<TYPE>.png (transparent
## 160x120) and thumbs/MANIFEST.txt (engine version, camera, sha256 per PNG).

const Defs = preload("res://src/GodotClient/Scripts/one_shard_defs.gd")
const BuildingView = preload("res://src/GodotClient3D/Scripts/production_building_view_3d.gd")
const RoadView = preload("res://src/GodotClient3D/Scripts/production_road_view_3d.gd")

const OUT_DIR := "res://assets/settlement3d/runtime/interface/thumbs/"
const SIZE := Vector2i(160, 120)
const YAW_DEG := 45.0
const PITCH_DEG := -32.0
const TYPES := [
	"ROAD", "HOUSE", "LUMBER_CAMP", "QUARRY", "FARM", "SAWMILL", "BAKERY",
	"STOREHOUSE", "WALL", "WATCHTOWER", "BARRACKS", "LUMEN_PILLAR", "CLAIMANT_OUTPOST", "CLEAR_AREA",
	"TOWN_HALL", "CASTLE",
]

var viewport: SubViewport
var camera: Camera3D
var stage: Node3D


func _init() -> void:
	call_deferred("_run")


func _run() -> void:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT_DIR))
	viewport = SubViewport.new()
	viewport.size = SIZE * 2
	viewport.transparent_bg = true
	viewport.own_world_3d = true
	viewport.msaa_3d = Viewport.MSAA_4X
	viewport.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	root.add_child(viewport)
	var env_node := WorldEnvironment.new()
	var env := Environment.new()
	env.background_mode = Environment.BG_CLEAR_COLOR
	env.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	env.ambient_light_color = Color(0.78, 0.8, 0.86)
	env.ambient_light_energy = 0.75
	env.tonemap_mode = Environment.TONE_MAPPER_FILMIC
	env_node.environment = env
	viewport.add_child(env_node)
	var sun := DirectionalLight3D.new()
	sun.rotation_degrees = Vector3(-50.0, 30.0, 0.0)
	sun.light_energy = 1.25
	sun.light_color = Color(1.0, 0.95, 0.86)
	sun.shadow_enabled = true
	viewport.add_child(sun)
	var fill := DirectionalLight3D.new()
	fill.rotation_degrees = Vector3(-25.0, -140.0, 0.0)
	fill.light_energy = 0.35
	fill.light_color = Color(0.7, 0.8, 1.0)
	viewport.add_child(fill)
	camera = Camera3D.new()
	camera.projection = Camera3D.PROJECTION_ORTHOGONAL
	camera.current = true
	viewport.add_child(camera)
	var manifest := PackedStringArray()
	manifest.append("# Building thumbnails (T-SNS-UI Look lift). Generated by tools/render_building_thumbnails.gd")
	manifest.append("# engine %s; %dx%d; ortho camera yaw %.0f pitch %.0f; transparent background" % [Engine.get_version_info().get("string", ""), SIZE.x, SIZE.y, YAW_DEG, PITCH_DEG])
	manifest.append("# Source models: the game's own building views (project-authored opening_style meshes; KayKit CC0 props where the view adds them). Not KayKit building models.")
	for type_name in TYPES:
		stage = Node3D.new()
		viewport.add_child(stage)
		_build_subject(String(type_name))
		for _i in 3:
			await process_frame
		_hide_helpers(stage)
		var box := _visual_aabb(stage)
		_add_plinth(box)
		box = _visual_aabb(stage)
		_frame_camera(box)
		for _i in 4:
			await process_frame
		await RenderingServer.frame_post_draw
		var image := viewport.get_texture().get_image()
		image.resize(SIZE.x, SIZE.y, Image.INTERPOLATE_LANCZOS)
		var path := OUT_DIR + String(type_name) + ".png"
		image.save_png(path)
		var sha := FileAccess.get_sha256(path)
		manifest.append("%s  %s.png" % [sha, type_name])
		print("THUMB %s aabb=%s sha=%s" % [type_name, str(box), sha.substr(0, 12)])
		stage.queue_free()
		await process_frame
	var file := FileAccess.open(OUT_DIR + "MANIFEST.txt", FileAccess.WRITE)
	file.store_string("\n".join(manifest) + "\n")
	file.close()
	print("THUMBNAILS PASS %d" % TYPES.size())
	quit(0)


func _build_subject(type_name: String) -> void:
	match type_name:
		"ROAD":
			for i in 3:
				var road := RoadView.new()
				stage.add_child(road)
				road.configure(i + 1, Vector2i(10, 9 + i), 5 if i == 1 else (4 if i == 0 else 1), false)
		"CLEAR_AREA":
			var fir: PackedScene = load("res://assets/settlement3d/runtime/opening_style/fir.tscn")
			var rocks: PackedScene = load("res://assets/settlement3d/runtime/opening_style/rocks.tscn")
			var axe: PackedScene = load("res://assets/settlement3d/runtime/tools/axe.gltf")
			var tree := fir.instantiate() as Node3D
			stage.add_child(tree)
			var stone := rocks.instantiate() as Node3D
			stone.position = Vector3(0.9, 0.0, 0.5)
			stone.scale = Vector3.ONE * 0.8
			stage.add_child(stone)
			var tool := axe.instantiate() as Node3D
			tool.position = Vector3(-0.5, 0.05, 0.7)
			tool.rotation_degrees = Vector3(0, 30, 80)
			tool.scale = Vector3.ONE * 1.4
			stage.add_child(tool)
		_:
			var view := BuildingView.new()
			stage.add_child(view)
			var building_type := type_name
			var snapshot := {"id": 1, "type": building_type, "footprint": Defs.building_footprint("TOWN_HALL" if building_type == "CASTLE" else building_type), "rotation": 0, "construction": false, "hp": 100, "max_hp": 100}
			if building_type == "CASTLE":
				snapshot["type"] = "TOWN_HALL"
				snapshot["has_barracks"] = true
			if building_type == "WALL":
				snapshot["wall_mask"] = 5
			view.configure(snapshot)
			if view.has_method("set_selected"):
				view.set_selected(false)


func _hide_helpers(node: Node) -> void:
	for child in node.get_children():
		if child is Label3D or child is Area3D or child is Light3D or child is GPUParticles3D or child is CPUParticles3D:
			(child as Node3D).visible = false
		elif child is MeshInstance3D and String(child.name).to_lower().contains("selection"):
			(child as Node3D).visible = false
		_hide_helpers(child)


func _visual_aabb(node: Node) -> AABB:
	var result := AABB()
	var first := true
	for child in node.find_children("*", "VisualInstance3D", true, false):
		var visual := child as VisualInstance3D
		if not visual.is_visible_in_tree() or visual is Light3D:
			continue
		var box: AABB = visual.global_transform * visual.get_aabb()
		if box.size.length() < 0.001:
			continue
		result = box if first else result.merge(box)
		first = false
	return result


func _add_plinth(box: AABB) -> void:
	var plinth := MeshInstance3D.new()
	var mesh := CylinderMesh.new()
	var radius := maxf(box.size.x, box.size.z) * 0.56
	mesh.top_radius = radius
	mesh.bottom_radius = radius * 1.04
	mesh.height = 0.08
	mesh.radial_segments = 48
	var material := StandardMaterial3D.new()
	material.albedo_color = Color(0.36, 0.47, 0.26)
	material.roughness = 1.0
	mesh.material = material
	plinth.mesh = mesh
	plinth.position = Vector3(box.get_center().x, box.position.y - 0.04, box.get_center().z)
	stage.add_child(plinth)


func _frame_camera(box: AABB) -> void:
	var center := box.get_center()
	var basis := Basis.from_euler(Vector3(deg_to_rad(PITCH_DEG), deg_to_rad(YAW_DEG), 0.0))
	camera.global_transform = Transform3D(basis, center + basis.z * 40.0)
	# Fit the 8 AABB corners in camera space, keep a 2 % margin.
	var inv := camera.global_transform.affine_inverse()
	var min_v := Vector2(INF, INF)
	var max_v := Vector2(-INF, -INF)
	for i in 8:
		var p: Vector3 = inv * box.get_endpoint(i)
		min_v = Vector2(minf(min_v.x, p.x), minf(min_v.y, p.y))
		max_v = Vector2(maxf(max_v.x, p.x), maxf(max_v.y, p.y))
	var extent := max_v - min_v
	var aspect := float(SIZE.x) / float(SIZE.y)
	camera.size = maxf(extent.y, extent.x / aspect) * 1.02
	var mid := (min_v + max_v) * 0.5
	camera.global_transform.origin += camera.global_transform.basis.x * mid.x + camera.global_transform.basis.y * mid.y
	camera.near = 0.05
	camera.far = 200.0
